twig:
  default_path: "%kernel.project_dir%/templates"

  globals:
    batman: "Batman & Robin"
    front: "Vous êtes sur la partie front"
    admin: "Vous êtes sur la partie admin"
    gproducts: '@App\Globals\Products'

when@test:
  twig:
    strict_variables: true
